[project]
name = "pen-plotter"
version = "0.1.0"
description = "Environnement perso pour sketches de pen plotting."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "pillow",
    "pysometric",
    "requests>=2.34.2",
    "shapely",
    "vpype",
    "vpype-gcode>=0.13.0",
    "vsketch",
]

[tool.uv]
package = false

[tool.uv.sources]
pysometric = { git = "https://github.com/svoisen/pysometric.git" }
